[mgr]
show_hidden = false
ratio = [1, 3, 4]
linemode = "size_and_mtime"
mouse_events = []

[preview]
max_width = 2000
max_height = 2000

[plugin]
[[plugin.prepend_previewers]]
name = "*.md"
run  = 'piper -- CLICOLOR_FORCE=1 glow -s ~/git/dotfiles/yazi/glow/tokyo_night.json -w=$w "$1"'

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

[open]
rules = [
    { name = "*/", use = [ "edit", "code", "ncdu", "7zip" ] },

    { name = "*.tar", use = [ "extract", "edit", "reveal", "7zip" ] },
    { name = "*.tar.gz", use = [ "extract", "edit", "reveal", "7zip" ] },
    { name = "*.tgz", use = [ "extract", "edit", "reveal", "7zip" ] },
    { name = "*.tar.bz2", use = [ "extract", "edit", "reveal", "7zip" ] },
    { name = "*.tbz", use = [ "extract", "edit", "reveal", "7zip" ] },
    { name = "*.tbz2", use = [ "extract", "edit", "reveal", "7zip" ] },
    { name = "*.zip", use = [ "extract", "edit", "reveal", "7zip" ] },
    { name = "*.7z", use = [ "extract", "edit", "reveal", "7zip" ] },
    { name = "*.rar", use = [ "extract", "edit", "reveal", "7zip" ] },
    { name = "*.gz", use = [ "extract", "edit", "reveal", "7zip" ] },
    { name = "*.bz2", use = [ "extract", "edit", "reveal", "7zip" ] },
    { name = "*.lzma", use = [ "extract", "edit", "reveal", "7zip" ] },

    { name = "*", use = [ "edit", "reveal", "7zip" ] },
]

[opener]
edit = [
    { run = '$EDITOR "$@"', block = true, for = "macos" },
    { run = '$EDITOR "$@"', block = true, for = "unix" },
]

code = [
    { run = 'code "$1"', orphan = true, desc = "Code", for = "macos" },
    { run = 'code "$1"', orphan = true, desc = "Code", for = "unix" },
]

ncdu = [
    { run = 'ncdu --color dark "$1"', block = true, desc = "Ncdu", for = "macos" },
    { run = 'ncdu --color dark "$1"', block = true, desc = "Ncdu", for = "unix" },
]

reveal = [
    { run = 'open -R "$1"', orphan = true, desc = "Reveal in Finder", for = "macos" },
    { run = 'xdg-open "$1"', orphan = true, desc = "Open in File Manager", for = "unix" },
]

7zip = [
    { run = '7zz a "$1.7z" "$1"', desc = "Archive with 7zip", for = "macos" },
    { run = '7zz a "$1.7z" "$1"', desc = "Archive with 7zip", for = "unix" },
]

extract = [
    { run = 'set -e; for f in "$@"; do name=$(basename -- "$f"); case "$name" in *.tar|*.tar.*|*.tgz|*.txz|*.tbz|*.tbz2|*.tzst) tar -xf "$f" ;; *) 7zz x -y "$f" ;; esac; done', block = true, desc = "Extract archive(s)", for = "macos" },
    { run = 'set -e; for f in "$@"; do name=$(basename -- "$f"); case "$name" in *.tar|*.tar.*|*.tgz|*.txz|*.tbz|*.tbz2|*.tzst) tar -xf "$f" ;; *) 7zz x -y "$f" ;; esac; done', block = true, desc = "Extract archive(s)", for = "unix" },
]
