schemaVersion = 1

[catalogConfiguration]
customFolders = []
scriptsDirectories = []

    [[catalogConfiguration.folderDepthOverrides]]
    catalogIdentifier = 'TunaAutomation.ScriptsCatalog'
    depthRawValue = 3

    [[catalogConfiguration.folderDepthOverrides]]
    catalogIdentifier = 'TunaCore.UserFoldersCatalog'
    depthRawValue = 1

[hotkeys.app.activate]
carbonKeyCode = 49
carbonModifiers = 2048

[hotkeys.app.dictation]
carbonKeyCode = 9
carbonModifiers = 6912

[hotkeys.app.leaderMode]
carbonKeyCode = 49
carbonModifiers = 4096

[hotkeys.app.textMode]
carbonKeyCode = 49
carbonModifiers = 6912

[[hotkeys.custom]]
id = '0046BA0C-7125-487C-9FCA-F10A271A579B'
presentation = 'hidden'

    [hotkeys.custom.command]
    actionIdentifier = 'TunaCore.CommonActionsCatalog.Open'
    subjectIdentifier = 'TunaCore.AllApplicationsCatalog.Vivaldi'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 11
    carbonModifiers = 6912

[[hotkeys.custom]]
id = '33143714-29F8-496E-8CC3-BC12E9DF133C'
presentation = 'auto'

    [hotkeys.custom.command]
    actionIdentifier = 'TunaCore.CommonActionsCatalog.Open'
    subjectIdentifier = 'TunaCore.AllApplicationsCatalog.ChatGPT'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 8
    carbonModifiers = 6912

[[hotkeys.custom]]
id = '6C4FDB9D-6EFB-4553-8462-40E3EEC589A8'
presentation = 'auto'

    [hotkeys.custom.command]
    actionIdentifier = 'TunaCore.CommonActionsCatalog.Open'
    subjectIdentifier = 'TunaCore.AllApplicationsCatalog.Signal'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 1
    carbonModifiers = 6912

[[hotkeys.custom]]
id = '93F8E6DF-B1C1-44E0-A5A7-C30403D69C3D'
presentation = 'hidden'

    [hotkeys.custom.command]
    actionIdentifier = 'TunaCore.CommonActionsCatalog.Open'
    subjectIdentifier = 'TunaCore.AllApplicationsCatalog.kitty'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 17
    carbonModifiers = 6912

[[hotkeys.custom]]
id = 'BEC34E79-3803-4152-9EFA-003968B87615'
presentation = 'hidden'

    [hotkeys.custom.command]
    actionIdentifier = 'TunaCore.CommonActionsCatalog.Open'
    subjectIdentifier = 'TunaCore.AllApplicationsCatalog.Obsidian'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 31
    carbonModifiers = 6912

[[hotkeys.custom]]
id = 'CF540AA9-C695-4CA4-B552-9E9CEFBF7E45'
presentation = 'hidden'

    [hotkeys.custom.command]
    actionIdentifier = 'TunaCore.CommonActionsCatalog.Open'
    subjectIdentifier = 'TunaCore.AllApplicationsCatalog.Visual Studio Code'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 35
    carbonModifiers = 6912

[[leaderMode.bindings]]
iconPath = '/Applications/Vivaldi.app'
key = 'b'
label = 'Browser'

    [[leaderMode.bindings.children]]
    iconPath = '/Applications/Vivaldi.app'
    key = 's'
    url = 'tuna://run/url.https:%252F%252Fstart.cmvps.de/Open%20URL'

    [[leaderMode.bindings.children]]
    key = 'm'
    url = 'tuna://run/url.https:%252F%252Fmail.proton.me%252Fu%252F0%252Finbox/Open%20URL'

    [[leaderMode.bindings.children]]
    key = 'b'
    url = 'tuna://run/TunaCore.AllApplicationsCatalog.Vivaldi/Open'

[[leaderMode.bindings]]
iconPath = 'folder.fill'
key = 'f'
label = 'Finder'

    [[leaderMode.bindings.children]]
    key = 'D'
    url = 'tuna://run/path.%252FUsers%252Fclaus%252FDownloads/Open'

    [[leaderMode.bindings.children]]
    key = 'g'
    url = 'tuna://run/path.%252FUsers%252Fclaus%252Fgit/Open'

    [[leaderMode.bindings.children]]
    key = 'c'
    url = 'tuna://run/path.%252FUsers%252Fclaus%252FCloud/Open'

    [[leaderMode.bindings.children]]
    key = 'd'
    url = 'tuna://run/path.%252FUsers%252Fclaus%252FDocuments/Open'

[[leaderMode.bindings]]
iconPath = 'folder.fill'
key = 'y'
label = 'yazi'

    [[leaderMode.bindings.children]]
    iconPath = 'cloud.fill'
    key = 'c'
    url = "tuna://run/text.%252FUsers%252Fclaus%252F.local%252Fbin%252Fyazi-open.sh%2520~%252FCloud%250Aosascript%2520-e%2520'tell%2520application%2520%2522kitty%2522%2520to%2520activate'/Run%20Text%20as%20Shell%20Command"

    [[leaderMode.bindings.children]]
    iconPath = 'cloud.fill'
    key = 'd'
    url = "tuna://run/text.%252FUsers%252Fclaus%252F.local%252Fbin%252Fyazi-open.sh%2520~%252FDownloads%250Aosascript%2520-e%2520'tell%2520application%2520%2522kitty%2522%2520to%2520activate'/Run%20Text%20as%20Shell%20Command"

    [[leaderMode.bindings.children]]
    iconPath = 'cloud.fill'
    key = 'g'
    url = "tuna://run/text.%252FUsers%252Fclaus%252F.local%252Fbin%252Fyazi-open.sh%2520~%252Fgit%250Aosascript%2520-e%2520'tell%2520application%2520%2522kitty%2522%2520to%2520activate'/Run%20Text%20as%20Shell%20Command"

[[leaderMode.bindings]]
iconPath = '/Applications/kitty.app'
key = 't'
label = 'kitty'

    [[leaderMode.bindings.children]]
    key = 'd'
    url = 'tuna://run/text.kitty%2520ssh%2520dev/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    key = 'g'
    url = 'tuna://run/text.kitty%2520~%252Fgit/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    key = 't'
    url = 'tuna://run/TunaCore.AllApplicationsCatalog.kitty/Open'

[settings]
activationDoublePressTrigger = 'leftOption'
clipboardHistoryEnabled = false
clipboardHistoryRetention = 'sevenDays'
dictationActivationMode = 'toggle'
leaderModeCheatsheetBehavior = 'always'
leaderModeModifierConfiguration = 'optionGroupControlSticky'
leaderModeModifierTrigger = 'leftCommand'
shelfCatalogEnabled = false
shortcutDisplayUsesHyperSymbol = false
themeIdentifier = 'com.brnbw.tuna.themes.default'

[[smartLinks.entries]]
enabled = false
name = 'Bing'
requiresInput = true
template = 'https://www.bing.com/search?q={{input}}'

[[smartLinks.entries]]
enabled = false
name = 'DuckDuckGo'
requiresInput = true
template = 'https://duckduckgo.com/?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'GitHub'
requiresInput = true
template = 'https://github.com/search?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'Google'
requiresInput = true
template = 'https://www.google.com/search?q={{input}}'

[[smartLinks.entries]]
enabled = false
name = 'Stack Overflow'
requiresInput = true
template = 'https://stackoverflow.com/search?q={{input}}'

[[smartLinks.entries]]
enabled = false
name = 'Wikipedia'
requiresInput = true
template = 'https://en.wikipedia.org/wiki/Special:Search?search={{input}}'

[[smartLinks.entries]]
enabled = false
name = 'YouTube'
requiresInput = true
template = 'https://www.youtube.com/results?search_query={{input}}'